run:
  timeout: 2m
  tests: true
  build-tags: [ cairo ]
  skip-files:
    - ".*\\.pb\\.go$"
    - "function_test.go"
    - "expr_test.go"
    - "cairo_test.go"

linters:
  enable:
    - asciicheck
    - bodyclose
    - gochecknoinits
    - gofmt
    - goimports
    - gosec
    - misspell
    - unparam

    # The linters we need to enable ASAP.
    # Enabling would require significant changes.
    # - gochecknoglobals
    # - unconvert
    # - wrapcheck

    # The linters that would be nice to have in order of decreasing priority.
    # They are disabled now because they cause a lot of warnings that would require multiple changes.
    # - revive
    # - errorlint
    # - promlinter
    # - cyclop or gocyclo
    # - whitespace
    # - gomnd
    # - lll
    # - gocritic

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
