# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "bitbucket.org/tebeka/strftime"
  version = "0.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/JaderDias/movingmedian"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/go-expirecache"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/go-onlinestats"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/httputil"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/evmar/gocairo"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/grace"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/pidfile"

[[constraint]]
  name = "github.com/go-graphite/protocol"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/lomik/og-rek"

[[constraint]]
  branch = "master"
  name = "github.com/lomik/zapwriter"

[[constraint]]
  branch = "master"
  name = "github.com/mjibson/go-dsp"

[[constraint]]
  branch = "master"
  name = "github.com/peterbourgon/g2g"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/wangjohn/quickselect"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
